<?php

/**
 *hook_menu
 */
function picasa_album_menu() {
	$items = array();
	$items['admin/config/media/picasa_album'] = array(
		'title' => t('Settings Picasa album'),
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('picasa_album_settings'),
		'access arguments' => array('Manage picasa album')
	);
	//list of albums
	$items['picasa_album/albums'] = array(
		'title' => t('Photo albums'),
		'type' => MENU_SUGGESTED_ITEM,
		'page callback' => 'picasa_album_page',
		'access arguments' => array('access content')
	);
	
	//list of photos in album
	$items['picasa_album/photos/%'] = array(
		'title' => t('Picasa album photos'),
		'type' => MENU_CALLBACK,
		'page callback' => 'picasa_album_photos_page',
		'page arguments' => array(2),
		'access arguments' => array('access content')
	);
	
	return $items;
}
/**
 * obtain list of user albums
 */
function picasa_album_albums($userid) {
	$albums = array();
	if($userid) {	
		$xml = simplexml_load_file('https://picasaweb.google.com/data/feed/api/user/'.$userid);
		$xml->registerXPathNamespace('d', 'http://www.w3.org/2005/Atom');
		$entries = $xml->xpath('/d:feed/d:entry');
		foreach ($entries as $album) {
			$album->registerXPathNamespace('d', 'http://www.w3.org/2005/Atom');
			$albums[] = array(
				'id' => $album->xpath('.//gphoto:id')['0'],
				'title' => $album->title,
				'url' => $album->xpath('.//d:link[@type="text/html"]')['0']['href'],
				'thumb' => $album->xpath('.//media:group/media:thumbnail')['0']['url'],
			);
		}	
	}
	return $albums;	
}

/**
 * get list of photos
 * @return array $photos, each item is an array with the keys content (string image url) and thumbs (array of thumbs available)
 */ 
function picasa_album_photos($userid,$albumID) {
	$photos = array();
	if($userid && $albumID) {
		$xml = simplexml_load_file('https://picasaweb.google.com/data/feed/api/user/'.$userid.'/albumid/'.$albumID.'?imgmax=800');
		$xml->registerXPathNamespace('d', 'http://www.w3.org/2005/Atom');
		$entries = $xml->xpath('/d:feed/d:entry');
		foreach ($entries as $photo) {
			$photo->registerXPathNamespace('d', 'http://www.w3.org/2005/Atom');
			$photos[] = array(
				'content' => $photo->xpath('.//media:group/media:content')['0']['url'],
				'thumbs' => $photo->xpath('.//media:group/media:thumbnail'),
			);
		}
	}
	return $photos;
} 

/**
 * show photos in album
 */ 

function picasa_album_photos_page($albumID) {
	return array(
		'#photos' => picasa_album_photos(variable_get('picasa_album_user'),$albumID),
		'#theme' => 'picasa_album_photo_thumbs',
	);			
}

/**
 * show albums of user
 */
function picasa_album_page() {
	return array(
		'#albums' => picasa_album_albums(variable_get('picasa_album_user')),
		'#theme' => 'picasa_album_thumbs'
	);		
}


/**
 * Implements hook_block_info().
 */
 function picasa_album_block_info() {
 	return array('album_list' => array(
		'info' => t('Picasa user albums'),
	)
	);
 }

 /**
  * Implements hook_block_configure().
  */
function picasa_album_block_configure($delta = '') {
	$form = array();
	if ($delta == 'album_list') {	
		//n albums
		$form['picasa_album_number'] = array(
			'#type' => 'textfield',
			'#title' => t('Number of albums'),
			'#default_value' => variable_get('picasa_album_number',5),
			'#required' => TRUE,
			'#description' => t('The maximum number of albums listed')		
		);	
		
		//at random or date order
		
	}
	return $form;	
	
}

/**
 * Implements hook_block_save()
 */ 
 function picasa_album_block_save($delta = '', $edit = array()) {
	if ($delta == 'album_list') {
		variable_set('picasa_album_user', $edit['picasa_album_user']);
		variable_set('picasa_album_number', $edit['picasa_album_number']);
	}
 }
 	
 	
/**
 * Implements hook_block_view().
 */
 function picasa_album_block_view($delta = '') {
 	if ($delta == 'album_list') {
		$block['subject'] = t('Picasa albums');
		$block['content'] = array(
            '#theme' => 'picasa_album_list',
            '#albums' => picasa_album_albums(variable_get('picasa_album_user')),
        );
		return $block;
	}
 	
 }
 
 /**
  * hook_theme
  */
function picasa_album_theme($existing, $type, $theme, $path) {
	return array(
		'picasa_album_list' => array('variables' => array('albums' => array())),
		'picasa_album_thumbs' => array('variables' => array('albums' => array())),
		'picasa_album_photo_thumbs' => array('variables' => array('photos' => array()))
	);
	
}

/**
 * settings form module
 */
function picasa_album_settings() {
	$form = array();
	//user
	$form['picasa_album_user'] = array(
		'#type' => 'textfield',
		'#title' => t('Picasa user'),
		'#default_value' => variable_get('picasa_album_user','someone'),
		'#required' => TRUE,
		'#description' => t('The picasa user account whose public albums will be shown on module pages and blocks')
	);
	return system_settings_form($form);		
}

/**
 * theme function for title list in block
 */
function theme_picasa_album_list($variables) {
	$albums = $variables['albums'];
	$output = '<ul>';
	foreach($albums as $album) {
		$output .= '<li>'.l($album['title'],'picasa_album/photos/'.$album['id']).'</li>';
	}
	$output .= '</ul>';
	return $output;
}

/**
 * theme function for thumbs
 */
function theme_picasa_album_thumbs($variables) {
	$albums = $variables['albums'];
	$output = '<div id="picasa_album_thumbs">';
	foreach($albums as $album) {
		$output .= '<div class="album_thumb">
			<img src="'.$album['thumb'].'" alt="thumb">
			<p>'.l($album['title'],'picasa_album/photos/'.$album['id']).'</p>
			</div>';
	}
	$output .= '</div>';
	return $output;
}

function theme_picasa_album_photo_thumbs($variables) {
	$photos = $variables['photos'];
	$output = '<div id="picasa_album_thumbs">';
	$link_opt = array(
				"html"=>TRUE,
				"attributes"=>	
					array(
					"class"=>array("colorbox"),
					"rel" => "gallery-all"),					
				);
	foreach($photos as $photo) {
		$output .= '<div class="album_thumb">
			'.l('<img src="'.$photo['thumbs']['1']['url'].'" alt="thumb">',$photo['content'],$link_opt).'</div>';
	}
	$output .= '</div>';
	return $output;	
}

/**
 * hook_permission
 */ 
 function picasa_album_permission() {
	 return array(
		'Manage picasa album' => array(
			'title' => 'Administer picasa album module'
	));
 }
