<?php

/**
 *hook_menu
 */
function picasa_album_menu() {
	$items = array();
	$items['admin/config/media/picasa_album'] = array(
		'title' => t('Settings Picasa album'),
		'type' => MENU_NORMAL_ITEM,
		'page callback' => 'drupal_get_form',
		'page arguments' => array('picasa_album_settings'),
		'access arguments' => array('Manage picasa album')
	);
	//list of albums
	$items['picasa_album/albums'] = array(
		'title' => t('Photo albums'),
		'type' => MENU_SUGGESTED_ITEM,
		'page callback' => 'picasa_album_page',
		'access arguments' => array('access content')
	);
	
	//list of photos in album
	$items['picasa_album/photos/%'] = array(
		'title' => t('Picasa album photos'),
		'type' => MENU_SUGGESTED_ITEM,
		'page callback' => 'picasa_album_photos',
		'page arguments' => array(3),
		'access arguments' => array('access content')
	);
	
	return $items;
}
/**
 * obtain list of user albums
 */
function picasa_album_albums($userid) {
	$albums = array();
	if($userid) {	
		$xml = simplexml_load_file('https://picasaweb.google.com/data/feed/api/user/'.$userid);
		foreach ($xml->entry as $item) {
			$albums[] = array(
				'title' => (string) $item->title,		
				'url' => (string)$item->link[1]['href']
			);	
		}	
	}
	return $albums;	
}

/**
 * show photos in album
 */ 

function picasa_album_photos($albumID) {
	return array('#markup' => 'TODO');			
}

/**
 * show albums of user
 */
function picasa_album_page() {
	$variables['albums'] = picasa_album_albums(variable_get('picasa_album_user'));
	return array('#markup' => theme('picasa_album_list',$variables));		
}


/**
 * Implements hook_block_info().
 */
 function picasa_album_block_info() {
 	return array('album_list' => array(
		'info' => t('Picasa user albums'),
	)
	);
 }

 /**
  * Implements hook_block_configure().
  */
function picasa_album_block_configure($delta = '') {
	$form = array();
	if ($delta == 'album_list') {	
		//n albums
		$form['picasa_album_number'] = array(
			'#type' => 'textfield',
			'#title' => t('Number of albums'),
			'#default_value' => variable_get('picasa_album_number',5),
			'#required' => TRUE,
			'#description' => t('The maximum number of albums listed')		
		);	
		
		//at random or date order
		
	}
	return $form;	
	
}

/**
 * Implements hook_block_save()
 */ 
 function picasa_album_block_save($delta = '', $edit = array()) {
	if ($delta == 'album_list') {
		variable_set('picasa_album_user', $edit['picasa_album_user']);
		variable_set('picasa_album_number', $edit['picasa_album_number']);
	}
 }
 	
 	
/**
 * Implements hook_block_view().
 */
 function picasa_album_block_view($delta = '') {
 	if ($delta == 'album_list') {
		$block['subject'] = t('Picasa albums');
		$block['content'] = array(
            '#theme' => 'picasa_album_list',
            '#albums' => picasa_album_albums(variable_get('picasa_album_user')),
        );
		return $block;
	}
 	
 }
 
 /**
  * hook_theme
  */
function picasa_album_theme($existing, $type, $theme, $path) {
	return array(
		'picasa_album_list' => array('variables' => array('albums' => array()))
	);
	
}

/**
 * settings form module
 */
function picasa_album_settings() {
	$form = array();
	//user
	$form['picasa_album_user'] = array(
		'#type' => 'textfield',
		'#title' => t('Picasa user'),
		'#default_value' => variable_get('picasa_album_user','someone'),
		'#required' => TRUE,
		'#description' => t('The picasa user account whose public albums will be shown on module pages and blocks')
	);
	return system_settings_form($form);		
}

/**
 * theme function for title list in block
 */
function theme_picasa_album_list($variables) {
	$albums = $variables['albums'];
	$output = '<ul>';
	foreach($albums as $album) {
		$output .= '<li>'.l($album['title'],$album['url'],array('attributes' =>array('target' => '_blank'))).'</li>';
	}
	$output .= '</ul>';
	return $output;
}

/**
 * hook_permission
 */ 
 function picasa_album_permission() {
	 return array(
		'Manage picasa album' => array(
			'title' => 'Administer picasa album module'
	));
 }
